name: Go Playwright CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: your_user
          POSTGRES_PASSWORD: your_password
          POSTGRES_DB: your_database
        options: >-
          --health-cmd "pg_isready -U your_user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'  # Specify your Go version

    - name: Install dependencies
      run: go mod tidy

    - name: Install Playwright
      run: go run github.com/playwright-community/playwright-go/install

    - name: Run Tests
      run: go test ./... -v

    - name: Run Playwright Tests
      run: go run your_playwright_test_file.go  # Change to your Playwright test file
