name: Go Playwright CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Admin
          POSTGRES_DB: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod tidy

    - name: Install Playwright
      run: go get -d github.com/playwright-community/playwright-go && go run github.com/playwright-community/playwright-go/cmd/playwright install

    - name: Create Database Schema
      env:
        PGPASSWORD: Admin
      run: |
        psql -h localhost -U postgres -d postgres -c "CREATE SCHEMA akses_pengguna;"

    - name: Run Tests
      run: go test ./... -v

    - name: Run Playwright Tests
      run: npx playwright test tests/aplikasi.spec.js
